<?php
namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class UserSubscriptionPlanTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        \DB::table('user_subscription_plan')->delete();

        \DB::table('user_subscription_plan')->insert(
        	array(
			  	array('id' => '1','user_id' => '24','subscription_plan_id' => '14','name' => 'Premier','description' => '4 Products /Premier Plans','tagline' => 'Premier plans','duration' => '12','no_of_product' => '1','plan_type' => 'Paid','price' => '15.00','currency' => 'USD','customer_id' => NULL,'auto_renewal' => 'On','status' => 'Inactive','flow_type' => 'Custom','alert_subscription' => '1','created_at' => '2021-11-25 15:04:40','updated_at' => '2021-11-25 15:04:40'),
                array('id' => '2','user_id' => '28','subscription_plan_id' => '2','name' => 'Free Plan','description' => 'Free Plan Description','tagline' => '#Free Plan','duration' => '7','no_of_product' => '3','plan_type' => 'Free','price' => '0.00','currency' => '','customer_id' => 'cus_KRUc2CJzro95xx','auto_renewal' => 'On','status' => 'Inactive','flow_type' => NULL,'alert_subscription' => '0','created_at' => '2021-11-25 15:04:40','updated_at' => '2021-11-25 15:04:40'),
                array('id' => '3','user_id' => '29','subscription_plan_id' => '15','name' => 'Test','description' => 'sdg','tagline' => '35443','duration' => '2','no_of_product' => '4','plan_type' => 'Free','price' => '0.00','currency' => '','customer_id' => 'cus_KSJ42yNvZJJSmJ','auto_renewal' => 'On','status' => 'Inactive','flow_type' => 'Custom','alert_subscription' => '0','created_at' => '2021-11-25 15:04:40','updated_at' => '2021-11-25 15:04:40'),
                array('id' => '4','user_id' => '31','subscription_plan_id' => '3','name' => 'Premium','description' => 'Premium Description','tagline' => '#Premium','duration' => '3','no_of_product' => '5','plan_type' => 'Paid','price' => '200.00','currency' => 'USD','customer_id' => '','auto_renewal' => 'On','status' => 'Inactive','flow_type' => NULL,'alert_subscription' => '0','created_at' => '2021-11-25 15:04:40','updated_at' => '2021-11-25 15:04:40'),
                array('id' => '5','user_id' => '32','subscription_plan_id' => '3','name' => 'Premium','description' => 'Premium Description','tagline' => '#Premium','duration' => '3','no_of_product' => '5','plan_type' => 'Free','price' => '200.00','currency' => 'USD','customer_id' => NULL,'auto_renewal' => 'On','status' => 'Inactive','flow_type' => NULL,'alert_subscription' => '0','created_at' => '2021-11-25 15:04:40','updated_at' => '2021-11-25 15:04:40'),
                array('id' => '6','user_id' => '33','subscription_plan_id' => '2','name' => 'Free Plan','description' => 'Free Plan Description','tagline' => '#Free Plan','duration' => '7','no_of_product' => '3','plan_type' => 'Free','price' => '0.00','currency' => 'USD','customer_id' => NULL,'auto_renewal' => 'On','status' => 'Inactive','flow_type' => NULL,'alert_subscription' => '0','created_at' => '2021-11-25 15:04:40','updated_at' => '2021-11-25 15:04:40'),
                array('id' => '7','user_id' => '32','subscription_plan_id' => '3','name' => 'Premium','description' => 'Premium Description','tagline' => '#Premium','duration' => '3','no_of_product' => '5','plan_type' => 'Custom','price' => '100.00','currency' => 'USD','customer_id' => NULL,'auto_renewal' => 'On','status' => 'Inactive','flow_type' => NULL,'alert_subscription' => '0','created_at' => '2021-11-25 15:04:40','updated_at' => '2021-11-25 15:04:40'),
                array('id' => '8','user_id' => '28','subscription_plan_id' => '3','name' => 'Premium','description' => 'Premium Description','tagline' => '#Premium','duration' => '3','no_of_product' => '1','plan_type' => 'Custom','price' => '200.00','currency' => 'Rupee','customer_id' => NULL,'auto_renewal' => 'On','status' => 'Inactive','flow_type' => NULL,'alert_subscription' => '0','created_at' => '2021-11-25 15:04:40','updated_at' => '2021-11-25 15:04:40'),
                array('id' => '9','user_id' => '30','subscription_plan_id' => '3','name' => 'Premium','description' => 'Premium Description','tagline' => '#Premium','duration' => '3','no_of_product' => '15','plan_type' => 'Custom','price' => '154.00','currency' => 'USD','customer_id' => NULL,'auto_renewal' => 'On','status' => 'Inactive','flow_type' => NULL,'alert_subscription' => '0','created_at' => '2021-11-25 15:04:40','updated_at' => '2021-11-25 15:04:40'),
                array('id' => '10','user_id' => '30','subscription_plan_id' => '3','name' => 'Premium','description' => 'Premium Description','tagline' => '#Premium','duration' => '3','no_of_product' => '5','plan_type' => 'Paid','price' => '200.00','currency' => 'USD','customer_id' => '','auto_renewal' => 'On','status' => 'Inactive','flow_type' => NULL,'alert_subscription' => '0','created_at' => '2021-11-25 15:04:40','updated_at' => '2021-11-25 15:04:40'),
                array('id' => '11','user_id' => '34','subscription_plan_id' => '32','name' => '2 Product Plan Free','description' => '2 Product Plan Free','tagline' => '2 Product Plan Free','duration' => '1','no_of_product' => '2','plan_type' => 'Free','price' => '0.00','currency' => '','customer_id' => '','auto_renewal' => 'On','status' => 'Inactive','flow_type' => NULL,'alert_subscription' => '0','created_at' => '2021-11-25 15:04:40','updated_at' => '2021-11-25 15:04:40'),
                array('id' => '12','user_id' => '34','subscription_plan_id' => '3','name' => 'Premium','description' => 'Premium Description','tagline' => '#Premium','duration' => '8','no_of_product' => '10','plan_type' => 'Custom','price' => '200.00','currency' => 'USD','customer_id' => NULL,'auto_renewal' => 'On','status' => 'Inactive','flow_type' => NULL,'alert_subscription' => '0','created_at' => '2021-11-25 15:04:40','updated_at' => '2021-11-25 15:04:40'),
                array('id' => '13','user_id' => '3','subscription_plan_id' => '2','name' => 'Free Plan','description' => 'Free Plan Description','tagline' => '#Free Plan','duration' => '7','no_of_product' => '5','plan_type' => 'Free','price' => '0.00','currency' => '','customer_id' => NULL,'auto_renewal' => 'On','status' => 'Inactive','flow_type' => NULL,'alert_subscription' => '0','created_at' => '2021-11-25 15:04:40','updated_at' => '2021-11-25 15:04:40'),
                array('id' => '14','user_id' => '35','subscription_plan_id' => '3','name' => 'Premium','description' => '2 Products','tagline' => '#Premium','duration' => '8','no_of_product' => '2','plan_type' => 'Paid','price' => '20.00','currency' => 'USD','customer_id' => NULL,'auto_renewal' => 'On','status' => 'Inactive','flow_type' => NULL,'alert_subscription' => '1','created_at' => '2021-11-25 15:04:40','updated_at' => '2021-11-25 15:04:40'),
                array('id' => '15','user_id' => '35','subscription_plan_id' => '3','name' => 'Premium','description' => 'Premium Description','tagline' => '#Premium','duration' => '8','no_of_product' => '10','plan_type' => 'Custom','price' => '20.00','currency' => 'USD','customer_id' => NULL,'auto_renewal' => 'On','status' => 'Inactive','flow_type' => NULL,'alert_subscription' => '0','created_at' => '2021-11-25 15:04:40','updated_at' => '2021-11-25 15:04:40'),
                array('id' => '16','user_id' => '37','subscription_plan_id' => '3','name' => 'Premium','description' => '2 Products','tagline' => '#Premium','duration' => '8','no_of_product' => '2','plan_type' => 'Paid','price' => '20.00','currency' => 'USD','customer_id' => NULL,'auto_renewal' => 'On','status' => 'Inactive','flow_type' => NULL,'alert_subscription' => '0','created_at' => '2021-11-25 15:04:41','updated_at' => '2021-11-25 15:04:41'),
                array('id' => '17','user_id' => '38','subscription_plan_id' => '27','name' => '5 Plan','description' => 'TEst','tagline' => 'Test','duration' => '1','no_of_product' => '3','plan_type' => 'Paid','price' => '5.00','currency' => 'INR','customer_id' => NULL,'auto_renewal' => 'On','status' => 'Inactive','flow_type' => NULL,'alert_subscription' => '0','created_at' => '2021-11-25 15:04:40','updated_at' => '2021-11-25 15:04:40'),
                array('id' => '18','user_id' => '39','subscription_plan_id' => '16','name' => 'New plan','description' => '5products','tagline' => 'Enjoy ur services','duration' => '2','no_of_product' => '5','plan_type' => 'Paid','price' => '65.00','currency' => 'USD','customer_id' => NULL,'auto_renewal' => 'On','status' => 'Inactive','flow_type' => 'Custom','alert_subscription' => '1','created_at' => '2021-11-25 15:04:40','updated_at' => '2021-11-25 15:04:40'),
                array('id' => '19','user_id' => '41','subscription_plan_id' => '2','name' => 'Free Plan','description' => 'Free Plan Description','tagline' => 'A','duration' => '7','no_of_product' => '5','plan_type' => 'Free','price' => '0.00','currency' => 'USD','customer_id' => 'cus_KSCY8yVgav8467','auto_renewal' => 'On','status' => 'Inactive','flow_type' => 'Custom','alert_subscription' => '0','created_at' => '2021-11-25 15:04:40','updated_at' => '2021-11-25 15:04:40'),
                array('id' => '21','user_id' => '41','subscription_plan_id' => '3','name' => 'Premium','description' => 'Premium Description','tagline' => '#Premium','duration' => '8','no_of_product' => '1','plan_type' => 'Custom','price' => '20.00','currency' => 'USD','customer_id' => NULL,'auto_renewal' => 'On','status' => 'Inactive','flow_type' => NULL,'alert_subscription' => '0','created_at' => '2021-11-25 15:04:40','updated_at' => '2021-11-25 15:04:40'),
                array('id' => '23','user_id' => '40','subscription_plan_id' => '14','name' => 'Premier','description' => '4 Products /Premier Plans','tagline' => 'Premier plans','duration' => '12','no_of_product' => '1','plan_type' => 'Custom','price' => '31.00','currency' => 'USD','customer_id' => NULL,'auto_renewal' => 'On','status' => 'Inactive','flow_type' => NULL,'alert_subscription' => '0','created_at' => '2021-11-25 15:04:40','updated_at' => '2021-11-25 15:04:40'),
                array('id' => '24','user_id' => '43','subscription_plan_id' => '3','name' => 'Premium','description' => 'Premium Description','tagline' => '#Premium','duration' => '8','no_of_product' => '2','plan_type' => 'Paid','price' => '18.00','currency' => 'USD','customer_id' => NULL,'auto_renewal' => 'Off','status' => 'Inactive','flow_type' => 'Custom','alert_subscription' => '0','created_at' => '2021-11-25 15:04:40','updated_at' => '2021-11-25 15:04:40'),
                array('id' => '27','user_id' => '42','subscription_plan_id' => '2','name' => 'Free Plan','description' => 'Free Plan Description','tagline' => '#Free Plan','duration' => '7','no_of_product' => '5','plan_type' => 'Free','price' => '0.00','currency' => 'USD','customer_id' => NULL,'auto_renewal' => 'On','status' => 'Inactive','flow_type' => 'Custom','alert_subscription' => '0','created_at' => '2021-11-25 15:04:40','updated_at' => '2021-11-25 15:04:40'),
                array('id' => '33','user_id' => '43','subscription_plan_id' => '14','name' => 'Premier','description' => 'Premier plans','tagline' => 'Premier plans','duration' => '12','no_of_product' => '200','plan_type' => 'Custom','price' => '35.00','currency' => 'USD','customer_id' => NULL,'auto_renewal' => 'On','status' => 'Inactive','flow_type' => NULL,'alert_subscription' => '0','created_at' => '2021-11-25 15:04:40','updated_at' => '2021-11-25 15:04:40'),
                array('id' => '34','user_id' => '49','subscription_plan_id' => '2','name' => 'Free Plan','description' => 'Free Plan Description','tagline' => '#Free Plan','duration' => '7','no_of_product' => '12','plan_type' => 'Free','price' => '0.00','currency' => 'USD','customer_id' => NULL,'auto_renewal' => 'On','status' => 'Inactive','flow_type' => NULL,'alert_subscription' => '0','created_at' => '2021-11-25 15:04:40','updated_at' => '2021-11-25 15:04:40'),
                array('id' => '35','user_id' => '50','subscription_plan_id' => '2','name' => 'Free Plan','description' => 'Free Plan Description','tagline' => '#Free Plan','duration' => '7','no_of_product' => '12','plan_type' => 'Free','price' => '0.00','currency' => 'USD','customer_id' => NULL,'auto_renewal' => 'On','status' => 'Inactive','flow_type' => NULL,'alert_subscription' => '0','created_at' => '2021-11-25 15:04:40','updated_at' => '2021-11-25 15:04:40'),
                array('id' => '36','user_id' => '51','subscription_plan_id' => '2','name' => 'Free Plan','description' => 'Free Plan Description','tagline' => '#Free Plan','duration' => '7','no_of_product' => '12','plan_type' => 'Free','price' => '0.00','currency' => 'USD','customer_id' => NULL,'auto_renewal' => 'On','status' => 'Inactive','flow_type' => NULL,'alert_subscription' => '0','created_at' => '2021-11-25 15:04:40','updated_at' => '2021-11-25 15:04:40'),
                array('id' => '37','user_id' => '53','subscription_plan_id' => '2','name' => 'Free Plan','description' => 'Free Plan Description','tagline' => '#Free Plan','duration' => '7','no_of_product' => '12','plan_type' => 'Free','price' => '0.00','currency' => 'USD','customer_id' => NULL,'auto_renewal' => 'On','status' => 'Inactive','flow_type' => NULL,'alert_subscription' => '0','created_at' => '2021-11-25 15:04:40','updated_at' => '2021-11-25 15:04:40'),
                array('id' => '38','user_id' => '54','subscription_plan_id' => '3','name' => 'Premium','description' => '2 Products','tagline' => '#Premium','duration' => '8','no_of_product' => '2','plan_type' => 'Custom','price' => '20.00','currency' => 'USD','customer_id' => NULL,'auto_renewal' => 'On','status' => 'Inactive','flow_type' => NULL,'alert_subscription' => '0','created_at' => '2021-11-25 15:04:40','updated_at' => '2021-11-25 15:04:40'),
                array('id' => '39','user_id' => '54','subscription_plan_id' => '3','name' => 'Premium','description' => '2 Products','tagline' => '#Premium','duration' => '8','no_of_product' => '2','plan_type' => 'Paid','price' => '20.00','currency' => 'USD','customer_id' => NULL,'auto_renewal' => 'On','status' => 'Inactive','flow_type' => NULL,'alert_subscription' => '0','created_at' => '2021-11-25 15:04:42','updated_at' => '2021-11-25 15:04:42'),
                array('id' => '40','user_id' => '58','subscription_plan_id' => '2','name' => 'Free Plan','description' => 'Free Plan Description','tagline' => '#Free Plan','duration' => '7','no_of_product' => '12','plan_type' => 'Free','price' => '0.00','currency' => 'USD','customer_id' => NULL,'auto_renewal' => 'On','status' => 'Inactive','flow_type' => NULL,'alert_subscription' => '0','created_at' => '2021-11-25 15:04:40','updated_at' => '2021-11-25 15:04:40'),
                array('id' => '41','user_id' => '59','subscription_plan_id' => '2','name' => 'Free Plan','description' => 'Free Plan Description','tagline' => '#Free Plan','duration' => '7','no_of_product' => '12','plan_type' => 'Free','price' => '0.00','currency' => 'USD','customer_id' => NULL,'auto_renewal' => 'On','status' => 'Inactive','flow_type' => NULL,'alert_subscription' => '0','created_at' => '2021-11-25 15:04:40','updated_at' => '2021-11-25 15:04:40'),
                array('id' => '42','user_id' => '44','subscription_plan_id' => '2','name' => 'Free Plan','description' => 'Free Plan Description','tagline' => '#Free Plan','duration' => '7','no_of_product' => '12','plan_type' => 'Free','price' => '0.00','currency' => 'USD','customer_id' => NULL,'auto_renewal' => 'On','status' => 'Inactive','flow_type' => NULL,'alert_subscription' => '0','created_at' => '2021-11-25 15:04:40','updated_at' => '2021-11-25 15:04:40')
			),
        );
    }
}
