<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
class UsersTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
		\DB::table('users')->delete();

		\DB::table('users')->insert(

			array(
			  array('id' => '3','referred_by' => NULL,'provider_id' => NULL,'user_type' => 'seller','name' => 'Mr. Seller','email' => 'seller@example.com','email_verified_at' => '2018-12-11 23:30:00','verification_code' => NULL,'new_email_verificiation_code' => NULL,'password' => '$2y$10$eUKRlkmm2TAug75cfGQ4i.WoUbcJ2uVPqUlVkox.cv4CCyGEIMQEm','remember_token' => '1zoU4eQxnOC5yxRWLsTzMNBPpJuOvTk4g3GMUVYIrbGijiXHOfIlFq0wHrIn','device_token' => NULL,'avatar' => 'https://lh3.googleusercontent.com/-7OnRtLyua5Q/AAAAAAAAAAI/AAAAAAAADRk/VqWKMl4f8CI/photo.jpg?sz=50','avatar_original' => NULL,'address' => 'Demo address','country' => 'US','city' => 'Demo city','postal_code' => '1234','phone' => NULL,'balance' => '0.00','banned' => '0','referral_code' => '3dLUoHsR1l','customer_package_id' => NULL,'remaining_uploads' => NULL,'created_at' => '2018-10-07 10:12:57','updated_at' => '2020-03-05 07:03:22'),
			  array('id' => '8','referred_by' => NULL,'provider_id' => NULL,'user_type' => 'admin','name' => 'Mr. Customer','email' => 'admin@gmail.com','email_verified_at' => '2018-12-11 23:30:00','verification_code' => NULL,'new_email_verificiation_code' => NULL,'password' => '$2y$10$eUKRlkmm2TAug75cfGQ4i.WoUbcJ2uVPqUlVkox.cv4CCyGEIMQEm','remember_token' => '35ZfFJh7tRSHPLYGJpIH4dUptHa6B6CSIINK8vdM7Y4iI92eH9U1dDncoW5f','device_token' => NULL,'avatar' => 'https://lh3.googleusercontent.com/-7OnRtLyua5Q/AAAAAAAAAAI/AAAAAAAADRk/VqWKMl4f8CI/photo.jpg?sz=50','avatar_original' => NULL,'address' => 'Demo address','country' => 'US','city' => 'Demo city','postal_code' => '1234','phone' => NULL,'balance' => '0.00','banned' => '0','referral_code' => '8zJTyXTlTT','customer_package_id' => NULL,'remaining_uploads' => NULL,'created_at' => '2018-10-07 10:12:57','updated_at' => '2020-03-03 09:56:11'),
			  array('id' => '9','referred_by' => NULL,'provider_id' => NULL,'user_type' => 'seller','name' => 'Merchant','email' => 'trioanglecliqbuy@gmail.com','email_verified_at' => '2021-09-14 06:09:58','verification_code' => NULL,'new_email_verificiation_code' => NULL,'password' => '$2y$10$s4wQPQTYXpc9Mmi5FCbD8ujIj57ZPS50vndWv1FBif79SbCC19nay','remember_token' => 'vGhA0vFB6GF5TtfqE1A9l1itZUC2t492mjx81dkQFHG8tt572wzu5fEExOZt','device_token' => 'dw3WtGPYSRqEV03S7HtXL8:APA91bFvOGxwk_i0AUnUrzT5iG6B87yKgktnYNVmTUmpbjPHmjz8ZV8ajm4yn-TgfLNC36y8C7MlzFOSVy3Deues4ql9Fnfy33s3pHynqJSpayIzkzZGDcKdvUxMyHY0tOptG8zSIbRH','avatar' => NULL,'avatar_original' => NULL,'address' => NULL,'country' => NULL,'city' => NULL,'postal_code' => NULL,'phone' => NULL,'balance' => '0.00','banned' => '0','referral_code' => NULL,'customer_package_id' => NULL,'remaining_uploads' => '0','created_at' => '2021-09-14 06:02:40','updated_at' => '2021-11-23 23:49:27'),
			  array('id' => '13','referred_by' => NULL,'provider_id' => NULL,'user_type' => 'customer','name' => 'Mick','email' => 'mick@gmail.com','email_verified_at' => '2021-09-18 06:09:42','verification_code' => NULL,'new_email_verificiation_code' => NULL,'password' => '$2y$10$/GyHA4vuSn7yClMp9uNtDeV4YV/2n7gveRURhMwSKfzqPY6zUuYC2','remember_token' => NULL,'device_token' => NULL,'avatar' => NULL,'avatar_original' => NULL,'address' => NULL,'country' => NULL,'city' => NULL,'postal_code' => NULL,'phone' => NULL,'balance' => '0.00','banned' => '0','referral_code' => NULL,'customer_package_id' => NULL,'remaining_uploads' => '0','created_at' => '2021-09-18 06:52:42','updated_at' => '2021-09-18 06:52:42'),
			  array('id' => '14','referred_by' => NULL,'provider_id' => NULL,'user_type' => 'customer','name' => 'test','email' => 'asfdghjghss@gmail.com','email_verified_at' => '2021-09-22 05:09:40','verification_code' => NULL,'new_email_verificiation_code' => NULL,'password' => '$2y$10$CiH.ykSFuQz1mTWQkl4Z2uDKrmPDEgXyndC7lyJyEL4CrVEH1x2qu','remember_token' => NULL,'device_token' => NULL,'avatar' => NULL,'avatar_original' => NULL,'address' => NULL,'country' => NULL,'city' => NULL,'postal_code' => NULL,'phone' => NULL,'balance' => '0.00','banned' => '0','referral_code' => NULL,'customer_package_id' => NULL,'remaining_uploads' => '0','created_at' => '2021-09-22 05:01:40','updated_at' => '2021-09-22 05:01:40'),
			  array('id' => '15','referred_by' => NULL,'provider_id' => NULL,'user_type' => 'customer','name' => 'test','email' => 'test@gmail.com','email_verified_at' => '2021-09-23 10:09:00','verification_code' => NULL,'new_email_verificiation_code' => NULL,'password' => '$2y$10$Ol9B6E6jyT880Pfl2UPpSus1dM0E5O3kXID/JPjHTAUOYh1ODaMu6','remember_token' => NULL,'device_token' => NULL,'avatar' => NULL,'avatar_original' => NULL,'address' => NULL,'country' => NULL,'city' => NULL,'postal_code' => NULL,'phone' => NULL,'balance' => '0.00','banned' => '0','referral_code' => NULL,'customer_package_id' => NULL,'remaining_uploads' => '0','created_at' => '2021-09-23 10:56:00','updated_at' => '2021-09-23 10:56:00'),
			  array('id' => '16','referred_by' => NULL,'provider_id' => NULL,'user_type' => 'customer','name' => 'Anish','email' => 'anishsuriya1@gmail.com','email_verified_at' => '2021-09-27 16:39:38','verification_code' => NULL,'new_email_verificiation_code' => NULL,'password' => '$2y$10$59JG/Qz1QVpQJufvsctpluXAcwkcRLp5u9KPdFG4WRwtUMde6Fq2e','remember_token' => 'JYdgKb7m43vBh51ZU0EaMCnGHV53lJg2Dy69eh4pv8V9vV2I77mY2aNLurml','device_token' => NULL,'avatar' => NULL,'avatar_original' => NULL,'address' => NULL,'country' => NULL,'city' => NULL,'postal_code' => NULL,'phone' => NULL,'balance' => '0.00','banned' => '0','referral_code' => NULL,'customer_package_id' => NULL,'remaining_uploads' => '0','created_at' => '2021-09-27 17:19:38','updated_at' => '2021-09-27 17:19:38'),
			  array('id' => '18','referred_by' => NULL,'provider_id' => NULL,'user_type' => 'seller','name' => 'pink doll','email' => 'doll@gmail.com','email_verified_at' => '2021-09-28 16:39:53','verification_code' => NULL,'new_email_verificiation_code' => NULL,'password' => '$2y$10$5STp4o5zI8R1BwGX.jnrTuYH5DaMiDHhATmuvSEiYbej1U7HveG86','remember_token' => 'UNgUqlWdObsyzTRniB4Rag7k4Mj37O8ONB8yPZJ6HheeqGUuTfEwW1fZrhAD','device_token' => NULL,'avatar' => NULL,'avatar_original' => NULL,'address' => NULL,'country' => NULL,'city' => NULL,'postal_code' => NULL,'phone' => NULL,'balance' => '0.00','banned' => '0','referral_code' => NULL,'customer_package_id' => NULL,'remaining_uploads' => '0','created_at' => '2021-09-28 17:06:46','updated_at' => '2021-09-28 17:12:53'),
			  array('id' => '19','referred_by' => NULL,'provider_id' => NULL,'user_type' => 'staff','name' => 'Trickster','email' => 'Tricksterke@gmail.com','email_verified_at' => NULL,'verification_code' => NULL,'new_email_verificiation_code' => NULL,'password' => '$2y$10$yAGcmyDnOiPTe2nkANRPgeY7b3OXCqEJVioZVVQsJFZ/IHAE1JS1W','remember_token' => NULL,'device_token' => NULL,'avatar' => NULL,'avatar_original' => NULL,'address' => NULL,'country' => NULL,'city' => NULL,'postal_code' => NULL,'phone' => '984124575','balance' => '0.00','banned' => '0','referral_code' => NULL,'customer_package_id' => NULL,'remaining_uploads' => '0','created_at' => '2021-09-28 18:23:25','updated_at' => '2021-10-18 04:25:24'),
			  array('id' => '21','referred_by' => NULL,'provider_id' => NULL,'user_type' => 'customer','name' => 'Kathir','email' => 'kathir@gmail.com','email_verified_at' => '2021-10-02 04:40:50','verification_code' => NULL,'new_email_verificiation_code' => NULL,'password' => '$2y$10$c0K4hmwaJDXNo93RmZ8AFupfXtmiEo.K9wYXsXWhAdaA4LemZD.Hm','remember_token' => NULL,'device_token' => NULL,'avatar' => NULL,'avatar_original' => NULL,'address' => NULL,'country' => NULL,'city' => NULL,'postal_code' => NULL,'phone' => NULL,'balance' => '0.00','banned' => '0','referral_code' => NULL,'customer_package_id' => NULL,'remaining_uploads' => '0','created_at' => '2021-10-02 04:54:50','updated_at' => '2021-10-02 04:54:50'),
			  array('id' => '22','referred_by' => NULL,'provider_id' => NULL,'user_type' => 'seller','name' => 'moncef hamza','email' => 'pharmashop.dz@gmail.com','email_verified_at' => '2021-10-07 12:40:51','verification_code' => NULL,'new_email_verificiation_code' => NULL,'password' => '$2y$10$FpF4t21wGV2QYO6x6vMQ2evP8iw7eJ0ew2fXT3zhWmnSAUSgN4AgO','remember_token' => NULL,'device_token' => NULL,'avatar' => NULL,'avatar_original' => NULL,'address' => NULL,'country' => NULL,'city' => NULL,'postal_code' => NULL,'phone' => NULL,'balance' => '0.00','banned' => '0','referral_code' => NULL,'customer_package_id' => NULL,'remaining_uploads' => '0','created_at' => '2021-10-07 12:34:51','updated_at' => '2021-10-07 12:34:51'),
			  array('id' => '23','referred_by' => NULL,'provider_id' => NULL,'user_type' => 'customer','name' => 'kk','email' => 'moncefh@gmail.com','email_verified_at' => '2021-10-07 12:40:17','verification_code' => NULL,'new_email_verificiation_code' => NULL,'password' => '$2y$10$4LJ2H2n3UkJi5cVtE5BsOeMRrqZaZD6QCmr/EZr.D32oO92/kVud.','remember_token' => NULL,'device_token' => NULL,'avatar' => NULL,'avatar_original' => NULL,'address' => NULL,'country' => NULL,'city' => NULL,'postal_code' => NULL,'phone' => NULL,'balance' => '0.00','banned' => '0','referral_code' => NULL,'customer_package_id' => NULL,'remaining_uploads' => '0','created_at' => '2021-10-07 13:11:17','updated_at' => '2021-10-07 13:11:17'),
			  array('id' => '24','referred_by' => NULL,'provider_id' => NULL,'user_type' => 'seller','name' => 'Pharma delivery','email' => 'Popo@gmail.com','email_verified_at' => '2021-10-07 22:40:52','verification_code' => NULL,'new_email_verificiation_code' => NULL,'password' => '$2y$10$3/71te.hyKRRHw3C1kGpM.O.rSPmq47sNFcHGzGridzxK0sqswfZm','remember_token' => NULL,'device_token' => NULL,'avatar' => NULL,'avatar_original' => NULL,'address' => NULL,'country' => NULL,'city' => NULL,'postal_code' => NULL,'phone' => NULL,'balance' => '0.00','banned' => '0','referral_code' => NULL,'customer_package_id' => NULL,'remaining_uploads' => '0','created_at' => '2021-10-07 23:20:52','updated_at' => '2021-10-07 23:20:52'),
			  array('id' => '25','referred_by' => NULL,'provider_id' => NULL,'user_type' => 'seller','name' => 'Madurai Outlet','email' => 'vismithanbe@gmail.com','email_verified_at' => '2021-10-08 00:40:07','verification_code' => NULL,'new_email_verificiation_code' => NULL,'password' => '$2y$10$ctD7FugxGLgD1x2ZAjiSs.npJ6dQI4VpxcvfKL9iBUuvQ4z6WkiBS','remember_token' => NULL,'device_token' => NULL,'avatar' => NULL,'avatar_original' => NULL,'address' => NULL,'country' => NULL,'city' => NULL,'postal_code' => NULL,'phone' => NULL,'balance' => '0.00','banned' => '0','referral_code' => NULL,'customer_package_id' => NULL,'remaining_uploads' => '0','created_at' => '2021-10-08 01:18:07','updated_at' => '2021-10-09 06:33:01'),
			  array('id' => '26','referred_by' => NULL,'provider_id' => NULL,'user_type' => 'seller','name' => 'merci','email' => 'moncefhmz@gmail.com','email_verified_at' => '2021-10-08 06:40:47','verification_code' => NULL,'new_email_verificiation_code' => NULL,'password' => '$2y$10$rIN.59J9FTB705PmEFVdiekpjzCTB18f6pfDzZzUzHDKdkMi.ROdy','remember_token' => NULL,'device_token' => NULL,'avatar' => NULL,'avatar_original' => NULL,'address' => NULL,'country' => NULL,'city' => NULL,'postal_code' => NULL,'phone' => NULL,'balance' => '0.00','banned' => '0','referral_code' => NULL,'customer_package_id' => NULL,'remaining_uploads' => '0','created_at' => '2021-10-08 07:16:47','updated_at' => '2021-10-08 07:16:47'),
			  array('id' => '27','referred_by' => NULL,'provider_id' => '115659127161908212118','user_type' => 'customer','name' => 'Testing Team','email' => 'testing@trioangle.com','email_verified_at' => '2021-10-08 16:40:27','verification_code' => NULL,'new_email_verificiation_code' => NULL,'password' => NULL,'remember_token' => 'zAJTL19jFVC5yz9kS6CpmBqMJjZKeR7zUZYxO7FPRY5QmiHhKYH3Cgq9uzgJ','device_token' => NULL,'avatar' => NULL,'avatar_original' => NULL,'address' => NULL,'country' => NULL,'city' => NULL,'postal_code' => NULL,'phone' => NULL,'balance' => '0.00','banned' => '0','referral_code' => NULL,'customer_package_id' => NULL,'remaining_uploads' => '0','created_at' => '2021-10-08 16:50:27','updated_at' => '2021-10-08 16:50:27'),
			  array('id' => '29','referred_by' => NULL,'provider_id' => NULL,'user_type' => 'seller','name' => 'Coco','email' => 'Mohamed@gmail.com','email_verified_at' => '2021-10-09 06:40:19','verification_code' => NULL,'new_email_verificiation_code' => NULL,'password' => '$2y$10$KlogjKqE4ZeV6ExfZAd46eppJWlkWT7oTmh/q9Wv3Tyv5XCP0jFLy','remember_token' => 'npXhoNafERRGMkOMCKJ0f7alldWNDh53t6bfyVqQSjrBCSibC7vT98JBjlAo','device_token' => NULL,'avatar' => NULL,'avatar_original' => NULL,'address' => NULL,'country' => NULL,'city' => NULL,'postal_code' => NULL,'phone' => NULL,'balance' => '0.00','banned' => '0','referral_code' => NULL,'customer_package_id' => NULL,'remaining_uploads' => '0','created_at' => '2021-10-09 06:36:19','updated_at' => '2021-10-09 06:36:19'),
			  array('id' => '30','referred_by' => NULL,'provider_id' => NULL,'user_type' => 'seller','name' => 'parashop','email' => 'parashop@gmail.com','email_verified_at' => '2021-10-09 07:40:25','verification_code' => NULL,'new_email_verificiation_code' => NULL,'password' => '$2y$10$zlfAGjqiK5GUvEGdAD4yGelkiVLWkJkJFr3taFZBqAbt2Me0cwqPm','remember_token' => NULL,'device_token' => NULL,'avatar' => NULL,'avatar_original' => NULL,'address' => NULL,'country' => NULL,'city' => NULL,'postal_code' => NULL,'phone' => NULL,'balance' => '0.00','banned' => '0','referral_code' => NULL,'customer_package_id' => NULL,'remaining_uploads' => '0','created_at' => '2021-10-09 07:50:25','updated_at' => '2021-10-09 07:50:25'),
			  array('id' => '31','referred_by' => NULL,'provider_id' => NULL,'user_type' => 'seller','name' => 'coco chanel','email' => 'cocochanelle@gmail.com','email_verified_at' => '2021-10-09 07:40:30','verification_code' => NULL,'new_email_verificiation_code' => NULL,'password' => '$2y$10$prC8I.sdiQ.6nvq3KRGtTOR2OUNlyjNccnx42yP1BkXOYSk7sqlgW','remember_token' => NULL,'device_token' => NULL,'avatar' => NULL,'avatar_original' => NULL,'address' => NULL,'country' => NULL,'city' => NULL,'postal_code' => NULL,'phone' => NULL,'balance' => '0.00','banned' => '0','referral_code' => NULL,'customer_package_id' => NULL,'remaining_uploads' => '0','created_at' => '2021-10-09 08:01:30','updated_at' => '2021-10-09 08:01:30'),
			  array('id' => '32','referred_by' => NULL,'provider_id' => NULL,'user_type' => 'customer','name' => 'Francisco Alves','email' => 'franciscobarbosa99536@gmail.com','email_verified_at' => '2021-10-11 06:40:37','verification_code' => NULL,'new_email_verificiation_code' => NULL,'password' => '$2y$10$amcC0RjZDsrG/Qk3MUBBF.u260RlBwY1hlUYm/TSKAZ/NMFZS.nGy','remember_token' => NULL,'device_token' => NULL,'avatar' => NULL,'avatar_original' => NULL,'address' => NULL,'country' => NULL,'city' => NULL,'postal_code' => NULL,'phone' => NULL,'balance' => '0.00','banned' => '0','referral_code' => NULL,'customer_package_id' => NULL,'remaining_uploads' => '0','created_at' => '2021-10-11 06:44:37','updated_at' => '2021-10-11 06:44:37'),
			  array('id' => '33','referred_by' => NULL,'provider_id' => NULL,'user_type' => 'customer','name' => 'Joe','email' => 'joemathan.it@gmail.com','email_verified_at' => '2021-10-12 00:40:06','verification_code' => '727989','new_email_verificiation_code' => NULL,'password' => '$2y$10$3TGdm9Il7b13o3BvXzWUIeruk5Gf/nYVX8ARIJPTQSIE83k9d7Rly','remember_token' => 'L15j9S3PZLIelJ1mcx5tlyMcL4hRgXgITALAX5gXn9gdU8KJXdogX9YHs5Q0','device_token' => 'fnzCUrxqRuasxL8-JNhB7J:APA91bGOTnaGbHhUpP3e4P0sPcdL_woS7va2rjQlXRsZjqbCa-2rh1vbQt1c2yVDCOq5I8S9Q-N_NxxOGmKne_ROaCQz_tOsLEqB3wakC0vvm9xuyLgkzO0pLHWPucj8_daNMMbx52Bu','avatar' => NULL,'avatar_original' => '118','address' => NULL,'country' => NULL,'city' => NULL,'postal_code' => NULL,'phone' => NULL,'balance' => '0.00','banned' => '0','referral_code' => NULL,'customer_package_id' => NULL,'remaining_uploads' => '0','created_at' => '2021-10-12 01:08:06','updated_at' => '2021-11-23 01:58:25'),
			  array('id' => '34','referred_by' => NULL,'provider_id' => NULL,'user_type' => 'customer','name' => 'Prasanth','email' => 'prasanth1308@gmail.com','email_verified_at' => '2021-10-12 01:40:34','verification_code' => NULL,'new_email_verificiation_code' => NULL,'password' => '$2y$10$j4d/s8Gm7I5TsXp4cB7NmupVz2wA8JHO4zzFBLyCOWMeENBLyjxMq','remember_token' => NULL,'device_token' => NULL,'avatar' => NULL,'avatar_original' => NULL,'address' => NULL,'country' => NULL,'city' => NULL,'postal_code' => NULL,'phone' => NULL,'balance' => '0.00','banned' => '0','referral_code' => NULL,'customer_package_id' => NULL,'remaining_uploads' => '0','created_at' => '2021-10-12 01:51:34','updated_at' => '2021-10-12 01:51:34'),
			  array('id' => '35','referred_by' => NULL,'provider_id' => NULL,'user_type' => 'customer','name' => 'kjcy','email' => 'techtrioangle@gmail.com','email_verified_at' => '2021-10-12 20:40:20','verification_code' => NULL,'new_email_verificiation_code' => NULL,'password' => '$2y$10$AsXoXuxKrJJNZ5E54swkSurUrPyY30ZnyM.c5Uw/NtmxawQyenV.2','remember_token' => 'Zhn7PMKZOPZl07vNfhTy82UNpWElGLVf3nEp4doDNIrKNLvHKnHSgSLA46cZ','device_token' => NULL,'avatar' => NULL,'avatar_original' => NULL,'address' => NULL,'country' => NULL,'city' => NULL,'postal_code' => NULL,'phone' => NULL,'balance' => '0.00','banned' => '0','referral_code' => NULL,'customer_package_id' => NULL,'remaining_uploads' => '0','created_at' => '2021-10-12 20:32:20','updated_at' => '2021-10-12 20:32:20'),
			  array('id' => '36','referred_by' => NULL,'provider_id' => NULL,'user_type' => 'seller','name' => 'Kundamandaka','email' => 'sharuksir@gmail.com','email_verified_at' => '2021-10-12 20:40:26','verification_code' => NULL,'new_email_verificiation_code' => NULL,'password' => '$2y$10$CKf3p3FNPE1WhZKJiQO4U.d/7XgpdDgVRR1YyT6WcvA.222f94Qpu','remember_token' => NULL,'device_token' => NULL,'avatar' => NULL,'avatar_original' => NULL,'address' => NULL,'country' => NULL,'city' => NULL,'postal_code' => NULL,'phone' => NULL,'balance' => '0.00','banned' => '0','referral_code' => NULL,'customer_package_id' => NULL,'remaining_uploads' => '0','created_at' => '2021-10-12 20:56:26','updated_at' => '2021-10-12 20:56:26'),
			  array('id' => '37','referred_by' => NULL,'provider_id' => '110213540906374806955','user_type' => 'customer','name' => '19. Shivdatt','email' => 'hipatelshivdatt774@gmail.com','email_verified_at' => '2021-10-14 14:40:50','verification_code' => NULL,'new_email_verificiation_code' => NULL,'password' => NULL,'remember_token' => '2nooaecP6vHHZvu2XJe8w2JAcyo04FrJ5Wu4XXeoOerFpR401WIlP0qnpeXD','device_token' => NULL,'avatar' => NULL,'avatar_original' => NULL,'address' => NULL,'country' => NULL,'city' => NULL,'postal_code' => NULL,'phone' => NULL,'balance' => '0.00','banned' => '0','referral_code' => NULL,'customer_package_id' => NULL,'remaining_uploads' => '0','created_at' => '2021-10-14 14:43:50','updated_at' => '2021-10-14 14:43:50'),
			  array('id' => '38','referred_by' => NULL,'provider_id' => NULL,'user_type' => 'customer','name' => 'kumar','email' => 'kumar123@gmail.com','email_verified_at' => '2021-10-18 16:40:49','verification_code' => NULL,'new_email_verificiation_code' => NULL,'password' => '$2y$10$SXaY./2ORTYJ5X/6CYaocO7pQqLrpWUeGLh7QcL5JLaF8HdZq21tm','remember_token' => NULL,'device_token' => NULL,'avatar' => NULL,'avatar_original' => NULL,'address' => NULL,'country' => NULL,'city' => NULL,'postal_code' => NULL,'phone' => NULL,'balance' => '0.00','banned' => '0','referral_code' => NULL,'customer_package_id' => NULL,'remaining_uploads' => '0','created_at' => '2021-10-18 17:07:49','updated_at' => '2021-10-18 17:07:49'),
			  array('id' => '39','referred_by' => NULL,'provider_id' => NULL,'user_type' => 'customer','name' => 'Mick','email' => 'venkattriotest@gmail.com','email_verified_at' => '2021-10-18 20:40:47','verification_code' => NULL,'new_email_verificiation_code' => NULL,'password' => '$2y$10$IejYtLJjTK7RLAKa7KvNq.wbnkPy7Y8EUP3qbMfmsJVdGRTy7qGOW','remember_token' => 'hAdtifwXjWo4Emm6J4Yg9eguXZxXcXrkkRQC6bbGtKTEppXtPwgS811qUWOZ','device_token' => NULL,'avatar' => NULL,'avatar_original' => NULL,'address' => NULL,'country' => NULL,'city' => NULL,'postal_code' => NULL,'phone' => NULL,'balance' => '0.00','banned' => '0','referral_code' => NULL,'customer_package_id' => NULL,'remaining_uploads' => '0','created_at' => '2021-10-18 21:05:47','updated_at' => '2021-10-18 21:05:47'),
			  array('id' => '40','referred_by' => NULL,'provider_id' => NULL,'user_type' => 'customer','name' => 'kk','email' => 'krisnakumar89@gmail.com','email_verified_at' => '2021-11-06 15:41:36','verification_code' => '936076','new_email_verificiation_code' => NULL,'password' => '$2y$10$Y/XwE4vGEetftdrWoBnC3O0OSacJ6X9p/2ZDMTJPc07JjHeZw0TJq','remember_token' => NULL,'device_token' => NULL,'avatar' => NULL,'avatar_original' => NULL,'address' => NULL,'country' => NULL,'city' => NULL,'postal_code' => NULL,'phone' => NULL,'balance' => '0.00','banned' => '0','referral_code' => NULL,'customer_package_id' => NULL,'remaining_uploads' => '0','created_at' => '2021-11-06 15:50:36','updated_at' => '2021-11-06 15:50:36'),
			  array('id' => '41','referred_by' => NULL,'provider_id' => NULL,'user_type' => 'customer','name' => 'Monk','email' => 'haitianmonk@gmail.com','email_verified_at' => '2021-11-07 15:41:43','verification_code' => NULL,'new_email_verificiation_code' => NULL,'password' => '$2y$10$1bJE43gW6K/ONJzZ2p2w0uswkKiKO45a0gl7DGh15tFkjbACzyK2e','remember_token' => NULL,'device_token' => NULL,'avatar' => NULL,'avatar_original' => NULL,'address' => NULL,'country' => NULL,'city' => NULL,'postal_code' => NULL,'phone' => NULL,'balance' => '0.00','banned' => '0','referral_code' => NULL,'customer_package_id' => NULL,'remaining_uploads' => '0','created_at' => '2021-11-07 16:21:43','updated_at' => '2021-11-07 16:21:43'),
			  array('id' => '42','referred_by' => NULL,'provider_id' => NULL,'user_type' => 'customer','name' => 'kk','email' => 'krisnakumar.muruganandam@frontier.com','email_verified_at' => '2021-11-09 03:41:06','verification_code' => '426615','new_email_verificiation_code' => NULL,'password' => '$2y$10$lw2lrl818LlAlR5UHiKTiemyWZrGHJNMLP57B3.1NdxPlSEZ/NUz.','remember_token' => NULL,'device_token' => NULL,'avatar' => NULL,'avatar_original' => NULL,'address' => NULL,'country' => NULL,'city' => NULL,'postal_code' => NULL,'phone' => NULL,'balance' => '0.00','banned' => '0','referral_code' => NULL,'customer_package_id' => NULL,'remaining_uploads' => '0','created_at' => '2021-11-09 04:23:06','updated_at' => '2021-11-09 04:23:06'),
			  array('id' => '43','referred_by' => NULL,'provider_id' => NULL,'user_type' => 'customer','name' => 'kk','email' => 'krisnakumar.muruganandam@frontier.c','email_verified_at' => '2021-11-09 03:41:01','verification_code' => '141475','new_email_verificiation_code' => NULL,'password' => '$2y$10$0zQSibbzYNBf9BVzeXSoyOPKeUX4Ouwzw2poE1cYXRJYGTEo9o4rS','remember_token' => NULL,'device_token' => NULL,'avatar' => NULL,'avatar_original' => NULL,'address' => NULL,'country' => NULL,'city' => NULL,'postal_code' => NULL,'phone' => NULL,'balance' => '0.00','banned' => '0','referral_code' => NULL,'customer_package_id' => NULL,'remaining_uploads' => '0','created_at' => '2021-11-09 04:29:01','updated_at' => '2021-11-09 04:29:01'),
			  array('id' => '44','referred_by' => NULL,'provider_id' => NULL,'user_type' => 'customer','name' => 'mike hussy','email' => 'mikehussy@gmail.com','email_verified_at' => '2021-11-09 17:41:29','verification_code' => NULL,'new_email_verificiation_code' => NULL,'password' => '$2y$10$vflD6O4Cx7Pl4Ev9LkFuiuMt5NR2rXXMmTVSAhxme1YMhkLna6CBC','remember_token' => NULL,'device_token' => NULL,'avatar' => NULL,'avatar_original' => '119','address' => NULL,'country' => NULL,'city' => NULL,'postal_code' => NULL,'phone' => NULL,'balance' => '0.00','banned' => '0','referral_code' => NULL,'customer_package_id' => NULL,'remaining_uploads' => '0','created_at' => '2021-11-09 17:38:29','updated_at' => '2021-11-09 18:01:02'),
			  array('id' => '45','referred_by' => NULL,'provider_id' => NULL,'user_type' => 'seller','name' => 'Williamjames','email' => 'ringerjames@gmail.com','email_verified_at' => '2021-11-09 17:41:46','verification_code' => NULL,'new_email_verificiation_code' => NULL,'password' => '$2y$10$3BEZseYw/xxGBaSnEVhTTuz1jyziySJbtiujPrQMH5BIUFv6fjvEC','remember_token' => NULL,'device_token' => NULL,'avatar' => NULL,'avatar_original' => NULL,'address' => NULL,'country' => NULL,'city' => NULL,'postal_code' => NULL,'phone' => NULL,'balance' => '0.00','banned' => '0','referral_code' => NULL,'customer_package_id' => NULL,'remaining_uploads' => '0','created_at' => '2021-11-09 18:09:46','updated_at' => '2021-11-09 18:09:46'),
			  array('id' => '46','referred_by' => NULL,'provider_id' => NULL,'user_type' => 'customer','name' => 'dhsg','email' => 'rhsge@g.com','email_verified_at' => '2021-11-10 01:41:02','verification_code' => '314016','new_email_verificiation_code' => NULL,'password' => '$2y$10$jxF0QIWRnnRbQvHMMrnn..0AEva.H5rHwUPsKaTXzvxWNPEqDTViq','remember_token' => NULL,'device_token' => NULL,'avatar' => NULL,'avatar_original' => NULL,'address' => NULL,'country' => NULL,'city' => NULL,'postal_code' => NULL,'phone' => NULL,'balance' => '0.00','banned' => '0','referral_code' => NULL,'customer_package_id' => NULL,'remaining_uploads' => '0','created_at' => '2021-11-10 01:39:02','updated_at' => '2021-11-10 01:39:02'),
			  array('id' => '47','referred_by' => NULL,'provider_id' => NULL,'user_type' => 'customer','name' => 'dhsgdgs','email' => 'rhsgsge@g.com','email_verified_at' => '2021-11-10 01:41:53','verification_code' => '204050','new_email_verificiation_code' => NULL,'password' => '$2y$10$fUXShA1gPOKwRzCaNjym0.V6Xce88kP6Ldb7wG2/7iDk7zMR/FOXy','remember_token' => NULL,'device_token' => NULL,'avatar' => NULL,'avatar_original' => NULL,'address' => NULL,'country' => NULL,'city' => NULL,'postal_code' => NULL,'phone' => NULL,'balance' => '0.00','banned' => '0','referral_code' => NULL,'customer_package_id' => NULL,'remaining_uploads' => '0','created_at' => '2021-11-10 01:49:53','updated_at' => '2021-11-10 01:49:53'),
			  array('id' => '48','referred_by' => NULL,'provider_id' => NULL,'user_type' => 'customer','name' => 'makesh','email' => 'makesh123@gmail.com','email_verified_at' => '2021-11-10 16:41:02','verification_code' => NULL,'new_email_verificiation_code' => NULL,'password' => '$2y$10$sdj8ao9Qp63/2Dv0/aX4FuL36qu3cEY085tJIJgV6Yo7IJmpjihl6','remember_token' => NULL,'device_token' => NULL,'avatar' => NULL,'avatar_original' => NULL,'address' => NULL,'country' => NULL,'city' => NULL,'postal_code' => NULL,'phone' => NULL,'balance' => '0.00','banned' => '0','referral_code' => NULL,'customer_package_id' => NULL,'remaining_uploads' => '0','created_at' => '2021-11-10 16:36:02','updated_at' => '2021-11-10 16:36:02'),
			  array('id' => '49','referred_by' => NULL,'provider_id' => NULL,'user_type' => 'seller','name' => 'hasan','email' => 'hasan123@gmail.com','email_verified_at' => '2021-11-10 16:41:27','verification_code' => NULL,'new_email_verificiation_code' => NULL,'password' => '$2y$10$wy3fhep82iJrYVGb7fmgBOBxP2Pl9Q7EEF/LP/8fuyB6GOTbSaK6q','remember_token' => 'Rc34xa8XnHZ0pth3PtGE5qIAvBSw3ErvOdxhmKnlqz6K36eo97RxVRqSP0au','device_token' => NULL,'avatar' => NULL,'avatar_original' => NULL,'address' => NULL,'country' => NULL,'city' => NULL,'postal_code' => NULL,'phone' => NULL,'balance' => '0.00','banned' => '0','referral_code' => NULL,'customer_package_id' => NULL,'remaining_uploads' => '0','created_at' => '2021-11-10 16:42:52','updated_at' => '2021-11-10 16:45:27'),
			  array('id' => '50','referred_by' => NULL,'provider_id' => NULL,'user_type' => 'customer','name' => 'jokgokfgj','email' => 'hkkkohu@g.com','email_verified_at' => '2021-11-14 13:41:58','verification_code' => '655978','new_email_verificiation_code' => NULL,'password' => '$2y$10$2Al5VKvtxGb7IyQb95YjEuht.m0051L8iohveNobkzv8JPhE8BJrC','remember_token' => NULL,'device_token' => NULL,'avatar' => NULL,'avatar_original' => NULL,'address' => NULL,'country' => NULL,'city' => NULL,'postal_code' => NULL,'phone' => NULL,'balance' => '0.00','banned' => '0','referral_code' => NULL,'customer_package_id' => NULL,'remaining_uploads' => '0','created_at' => '2021-11-14 13:52:58','updated_at' => '2021-11-14 13:52:58'),
			  array('id' => '51','referred_by' => NULL,'provider_id' => NULL,'user_type' => 'staff','name' => 'Abc','email' => 'admin2@gmail.com','email_verified_at' => NULL,'verification_code' => NULL,'new_email_verificiation_code' => NULL,'password' => '$2y$10$o1cKX1/T0maNGmitD6Kqn.agIs.eoTg.M/XXYF0p9a0kYEqxW9Vfq','remember_token' => NULL,'device_token' => NULL,'avatar' => NULL,'avatar_original' => NULL,'address' => NULL,'country' => NULL,'city' => NULL,'postal_code' => NULL,'phone' => '153738828282','balance' => '0.00','banned' => '0','referral_code' => NULL,'customer_package_id' => NULL,'remaining_uploads' => '0','created_at' => '2021-11-17 02:05:35','updated_at' => '2021-11-17 02:05:35'),
			  array('id' => '52','referred_by' => NULL,'provider_id' => NULL,'user_type' => 'customer','name' => 'Muthu','email' => 'srmuthukumar95@gmail.com','email_verified_at' => '2021-11-17 15:41:57','verification_code' => NULL,'new_email_verificiation_code' => NULL,'password' => '$2y$10$K0IkZ5Ih9NwJklk4NrlsnO6VB5XJMAetD3Ti9YDaDQMh6IdlAB12q','remember_token' => NULL,'device_token' => NULL,'avatar' => NULL,'avatar_original' => NULL,'address' => NULL,'country' => NULL,'city' => NULL,'postal_code' => NULL,'phone' => NULL,'balance' => '0.00','banned' => '0','referral_code' => NULL,'customer_package_id' => NULL,'remaining_uploads' => '0','created_at' => '2021-11-17 15:41:57','updated_at' => '2021-11-17 15:41:57'),
			  array('id' => '53','referred_by' => NULL,'provider_id' => NULL,'user_type' => 'customer','name' => 'Senthil Kumar','email' => 'sk@gmail.com','email_verified_at' => '2021-11-18 21:41:52','verification_code' => NULL,'new_email_verificiation_code' => NULL,'password' => '$2y$10$ift39CfdDL4LiBU1dBCJ/elVF1g8zJNnRBh1jdcFKrsztfmIoyrIy','remember_token' => NULL,'device_token' => NULL,'avatar' => NULL,'avatar_original' => NULL,'address' => NULL,'country' => NULL,'city' => NULL,'postal_code' => NULL,'phone' => NULL,'balance' => '0.00','banned' => '0','referral_code' => NULL,'customer_package_id' => NULL,'remaining_uploads' => '0','created_at' => '2021-11-18 21:58:52','updated_at' => '2021-11-18 21:58:52'),
			  array('id' => '54','referred_by' => NULL,'provider_id' => NULL,'user_type' => 'customer','name' => 'raj','email' => 'raj@gmail.com','email_verified_at' => '2021-11-18 21:41:01','verification_code' => '994529','new_email_verificiation_code' => NULL,'password' => '$2y$10$L6HqC0XfQ.3cARwApu4nTupNsXCCcBXfZwQCRHZvNi7XWc86MMfbC','remember_token' => NULL,'device_token' => NULL,'avatar' => NULL,'avatar_original' => NULL,'address' => NULL,'country' => NULL,'city' => NULL,'postal_code' => NULL,'phone' => NULL,'balance' => '0.00','banned' => '0','referral_code' => NULL,'customer_package_id' => NULL,'remaining_uploads' => '0','created_at' => '2021-11-18 22:27:01','updated_at' => '2021-11-18 22:27:01'),
			  array('id' => '55','referred_by' => NULL,'provider_id' => NULL,'user_type' => 'customer','name' => 'mike','email' => 'mikem@ygmail.com','email_verified_at' => '2021-11-23 23:41:33','verification_code' => '315470','new_email_verificiation_code' => NULL,'password' => '$2y$10$0y7rjqtj/vTIVrXp9Yc8HuohvedfyyaaOUB7d4tezUjwziIIimlae','remember_token' => NULL,'device_token' => 'dw3WtGPYSRqEV03S7HtXL8:APA91bFvOGxwk_i0AUnUrzT5iG6B87yKgktnYNVmTUmpbjPHmjz8ZV8ajm4yn-TgfLNC36y8C7MlzFOSVy3Deues4ql9Fnfy33s3pHynqJSpayIzkzZGDcKdvUxMyHY0tOptG8zSIbRH','avatar' => NULL,'avatar_original' => NULL,'address' => NULL,'country' => NULL,'city' => NULL,'postal_code' => NULL,'phone' => NULL,'balance' => '100.00','banned' => '0','referral_code' => NULL,'customer_package_id' => NULL,'remaining_uploads' => '0','created_at' => '2021-11-24 00:07:33','updated_at' => '2021-11-24 00:59:55'),
			  array('id' => '56','referred_by' => NULL,'provider_id' => NULL,'user_type' => 'customer','name' => 'John','email' => 'john@ygmail.com','email_verified_at' => '2021-11-24 00:41:42','verification_code' => NULL,'new_email_verificiation_code' => NULL,'password' => '$2y$10$VcNNHr12b82AnPUZIBDK/ucs7d3FzSHIop657QAjjkPd2wldw.ZpG','remember_token' => NULL,'device_token' => NULL,'avatar' => NULL,'avatar_original' => NULL,'address' => NULL,'country' => NULL,'city' => NULL,'postal_code' => NULL,'phone' => NULL,'balance' => '0.00','banned' => '0','referral_code' => NULL,'customer_package_id' => NULL,'remaining_uploads' => '0','created_at' => '2021-11-24 00:48:42','updated_at' => '2021-11-24 00:48:42')
			),

		);
    }
}
